### ISSUE TITLE
Resource for installing vmods

### ISSUE THREAD

**Issue by KierranM** [sous-chefs/varnish#89]
A resource for installing vmods would be incredibly helpful. I see there is an implementation of this in the tests branch, but that seems to have gone stale.  Is there any chance of this being resurrected?

**Comment by martinb3** [comment]
@KierranM I think you're referring to https://github.com/rackspace-cookbooks/varnish/commit/a02d459ecdba1d4d74a18a677ab134ef8f3bbcd1. I agree that it would be helpful, but that implementation is all bash/execute resources; I'd love to see it be more something more idiomatic for a Chef recipe.

We're not doing a ton of active work on this cookbook, but we're happy to merge things, if you wanted to submit the feature as a contribution. We'll keep this open to remind us, though, in case we can go back to it and add this.

**Comment by eddieroger** [comment]
So what would need to be changed on the mentioned ref to make it more idiomatic Chef? I know my way around it, but not well enough to know what would be changed to make it happier in this case. What would need to be changed (at a high level) to make it acceptable? I'm willing to take on the change, but this the approach I'd have taken, since it's an automated manner of doing what I'd be doing in the shell anyway.

**Comment by martinb3** [comment]
I think writing a resource and provider for installing modules would be the 'chef' idiomatic way of doing this. Within the provider, the implementation could call Mixlib::ShellOut, or use other nested Chef providers to accomplish the goal (e.g. directory, remote_file,...).

**Comment by eddieroger** [comment]
That makes sense. I will take a stab at it, but that's hardly a promise it'll come out worthwhile (for any other onlookers who get their hopes up). Thanks for the clarification.
